### ISSUE TITLE
Upgrade build to modern version of React, Java and Gradle

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-starter-ui#94]
see: https://github.com/micronaut-projects/micronaut-starter-ui/pulls/app%2Fdependabot

**Comment by sdelamo** [comment]
@jeremyg484 do you have experience with React? Is this something you can help with?

**Comment by jeremyg484** [comment]
> @jeremyg484 do you have experience with React? Is this something you can help with?

@sdelamo Yes, I know React pretty well. As Tim noted in #95, updating to React 18 might not be an especially small task just because it would require updating the Material UI library as well. After a quick glance at https://mui.com/material-ui/migration/migration-v4/  and https://react.dev/blog/2022/03/08/react-18-upgrade-guide I'd say it's a day or so of work. Happy to tackle that if you think it worthwhile. 

Worth noting that React 18 drops support for Internet Explorer. I can't imagine there are many (if any) users of IE going to micronaut.io/launch, but we should verify that in the site stats before upgrading.
